name: journal-chatbot-dev

services:
  bot:
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile.dev
    depends_on:
      mastra:
        condition: service_started
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/bot:/app
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
    environment:
      WATCHPACK_POLLING: true
      CHOKIDAR_USEPOLLING: true
    env_file:
      - .env
    restart: unless-stopped

  mastra:
    build:
      context: .
      dockerfile: ./apps/mastra/Dockerfile.dev
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/mastra/src:/app/src
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
    environment:
      WATCHPACK_POLLING: true
      CHOKIDAR_USEPOLLING: true
    env_file:
      - .env
    ports:
      # for local development
      - '127.0.0.1:${MASTRA_PORT}:4111'
    restart: unless-stopped

  postgres:
    image: 'pgvector/pgvector:pg18-trixie'
    volumes:
      - postgres-data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      # for local development
      - '127.0.0.1:${POSTGRES_PORT}:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    user: postgres

volumes:
  postgres-data:
