name: journal-chatbot

services:
  bot:
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile
    depends_on:
      mastra:
        condition: service_started
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - journal-chatbot
    restart: unless-stopped

  mastra:
    build:
      context: .
      dockerfile: ./apps/mastra/Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - journal-chatbot
    restart: unless-stopped

  postgres:
    image: 'postgres:17-alpine'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      journal-chatbot:
        aliases:
          - postgres
      postgresus:
        aliases:
          - journal-chatbot-postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  journal-chatbot:
    driver: bridge
  postgresus:
    external: true

volumes:
  postgres-data:

